import React from 'react';

const user = {
  UserDetail: React.lazy(() => import('../views/user/UserDetail.jsx')),
};

const system = {
  CodeGroup: React.lazy(() => import('../views/system/code/CodeGroup.jsx')),
};

const root = {
  Login: React.lazy(() => import('../views/Login.jsx')),
  Home: React.lazy(() => import('../views/Home.jsx')),
  About: React.lazy(() => import('../views/About.jsx')),
};

const insanga = {
  UserMng: React.lazy(() => import('../views/insanga/setup/UserMng.jsx')),
  PartnerRegist: React.lazy(() => import('../views/insanga/partner/PartnerRegist.jsx')),
  ProcessShipment: React.lazy(() => import('../views/insanga/order/ProcessShipment.jsx')),
  OrderRegiste: React.lazy(() => import('../views/insanga/order/OrderRegiste.jsx')),
  NewOrder: React.lazy(() => import('../views/insanga/order/NewOrder.jsx')),
  ListMng: React.lazy(() => import('../views/insanga/order/ListMng.jsx')),
  HistorySearch: React.lazy(() => import('../views/insanga/order/HistorySearch.jsx')),
  DeliveryTrack: React.lazy(() => import('../views/insanga/order/DeliveryTrack.jsx')),
  PeriodByNewCustomerStatus: React.lazy(() => import('../views/insanga/monthData/PeriodByNewCustomerStatus.jsx')),
  MonthSalesStatus: React.lazy(() => import('../views/insanga/monthData/MonthSalesStatus.jsx')),
  MonthInStatus: React.lazy(() => import('../views/insanga/monthData/MonthInStatus.jsx')),
  ManagerBySalesStatus: React.lazy(() => import('../views/insanga/monthData/ManagerBySalesStatus.jsx')),
  GoodsBySalesAbc: React.lazy(() => import('../views/insanga/monthData/GoodsBySalesAbc.jsx')),
  CustomerMileageStatus: React.lazy(() => import('../views/insanga/monthData/CustomerMileageStatus.jsx')),
  CustomerBySalesAbc: React.lazy(() => import('../views/insanga/monthData/CustomerBySalesAbc.jsx')),
  CustomerByMidCateSalesStatus: React.lazy(() => import('../views/insanga/monthData/CustomerByMidCateSalesStatus.jsx')),
  CustomerBirthdaySearch: React.lazy(() => import('../views/insanga/monthData/CustomerBirthdaySearch.jsx')),
  AgentStockStatus: React.lazy(() => import('../views/insanga/monthData/AgentStockStatus.jsx')),
  Main: React.lazy(() => import('../views/insanga/Main.jsx')),
  OrderMng: React.lazy(() => import('../views/insanga/inputMng/OrderMng.jsx')),
  IncomingSlipsMng: React.lazy(() => import('../views/insanga/inputMng/IncomingSlipsMng.jsx')),
  PriceMng: React.lazy(() => import('../views/insanga/goods/PriceMng.jsx')),
  GoodsViewDetail: React.lazy(() => import('../views/insanga/goods/GoodsViewDetail.jsx')),
  GoodsRegist: React.lazy(() => import('../views/insanga/goods/GoodsRegist.jsx')),
  LayoutType3: React.lazy(() => import('../views/insanga/dev/pub/LayoutType3.jsx')),
  LayoutType2: React.lazy(() => import('../views/insanga/dev/pub/LayoutType2.jsx')),
  LayoutType1: React.lazy(() => import('../views/insanga/dev/pub/LayoutType1.jsx')),
  Components: React.lazy(() => import('../views/insanga/dev/pub/Components.jsx')),
  DashBoard: React.lazy(() => import('../views/insanga/DashBoard.jsx')),
  Type3: React.lazy(() => import('../views/insanga/dashboard/Type3.jsx')),
  Type2: React.lazy(() => import('../views/insanga/dashboard/Type2.jsx')),
  Type1: React.lazy(() => import('../views/insanga/dashboard/Type1.jsx')),
  ShipInStatus: React.lazy(() => import('../views/insanga/dailyData/ShipInStatus.jsx')),
  SalesStatus: React.lazy(() => import('../views/insanga/dailyData/SalesStatus.jsx')),
  SalesPersonAusIpt: React.lazy(() => import('../views/insanga/dailyData/SalesPersonAusIpt.jsx')),
  ReceiptsStatus: React.lazy(() => import('../views/insanga/dailyData/ReceiptsStatus.jsx')),
  OrderByShipStatus: React.lazy(() => import('../views/insanga/dailyData/OrderByShipStatus.jsx')),
  OnlineSales: React.lazy(() => import('../views/insanga/dailyData/OnlineSales.jsx')),
  GwpUsageStatus: React.lazy(() => import('../views/insanga/dailyData/GwpUsageStatus.jsx')),
  CheckOrderShipHiistory: React.lazy(() => import('../views/insanga/dailyData/CheckOrderShipHiistory.jsx')),
  AgentStockMoveStatus: React.lazy(() => import('../views/insanga/dailyData/AgentStockMoveStatus.jsx')),
  SkinWorrySearch: React.lazy(() => import('../views/insanga/customer/SkinWorrySearch.jsx')),
  RepurchByStatus: React.lazy(() => import('../views/insanga/customer/RepurchByStatus.jsx')),
  PurchBySalesStatus: React.lazy(() => import('../views/insanga/customer/PurchBySalesStatus.jsx')),
  PurchByCustCntStatus: React.lazy(() => import('../views/insanga/customer/PurchByCustCntStatus.jsx')),
  ProductSearch: React.lazy(() => import('../views/insanga/customer/ProductSearch.jsx')),
  MonthRetentionStatus: React.lazy(() => import('../views/insanga/customer/MonthRetentionStatus.jsx')),
  MonthNewCustPurchCnt: React.lazy(() => import('../views/insanga/customer/MonthNewCustPurchCnt.jsx')),
  MonthExistCustPurchCnt: React.lazy(() => import('../views/insanga/customer/MonthExistCustPurchCnt.jsx')),
  GradeSalesStatus: React.lazy(() => import('../views/insanga/customer/GradeSalesStatus.jsx')),
  CustStatus: React.lazy(() => import('../views/insanga/customer/CustStatus.jsx')),
  CustPerformance: React.lazy(() => import('../views/insanga/customer/CustPerformance.jsx')),
  CustomerManage: React.lazy(() => import('../views/insanga/customer/CustomerManage.jsx')),
  CustomerInfoSearch: React.lazy(() => import('../views/insanga/customer/CustomerInfoSearch.jsx')),
  CustMileageStatus: React.lazy(() => import('../views/insanga/customer/CustMileageStatus.jsx')),
  CustMileageMng: React.lazy(() => import('../views/insanga/customer/CustMileageMng.jsx')),
  CustInformation: React.lazy(() => import('../views/insanga/customer/CustInformation.jsx')),
  CustBirthday: React.lazy(() => import('../views/insanga/customer/CustBirthday.jsx')),
  BrandSearch: React.lazy(() => import('../views/insanga/customer/BrandSearch.jsx')),
  AgentWeekCustCnt: React.lazy(() => import('../views/insanga/customer/AgentWeekCustCnt.jsx')),
  AgentPeriodCustCnt: React.lazy(() => import('../views/insanga/customer/AgentPeriodCustCnt.jsx')),
  AgentMonthCustCnt: React.lazy(() => import('../views/insanga/customer/AgentMonthCustCnt.jsx')),
  AgeBySalesStatus: React.lazy(() => import('../views/insanga/customer/AgeBySalesStatus.jsx')),
};

const home = {
  DashBoard: React.lazy(() => import('../views/home/DashBoard.jsx')),
  AnnounceBoard: React.lazy(() => import('../views/home/announce/AnnounceBoard.jsx')),
};

const crm = {
  DashBoard: React.lazy(() => import('../views/crm/DashBoard.jsx')),
};

// 🚀 자동 생성된 라우트 설정
const routeConfig = [
  { path: '/user/userdetail', name: 'UserDetail', component: user.UserDetail },
  { path: '/system/code/codegroup', name: 'CodeGroup', component: system.CodeGroup },
  { path: '/login', name: 'Login', component: root.Login },
  { path: '/insanga/setup/usermng', name: 'UserMng', component: insanga.UserMng },
  { path: '/insanga/partner/partnerregist', name: 'PartnerRegist', component: insanga.PartnerRegist },
  { path: '/insanga/order/processshipment', name: 'ProcessShipment', component: insanga.ProcessShipment },
  { path: '/insanga/order/orderregiste', name: 'OrderRegiste', component: insanga.OrderRegiste },
  { path: '/insanga/order/neworder', name: 'NewOrder', component: insanga.NewOrder },
  { path: '/insanga/order/listmng', name: 'ListMng', component: insanga.ListMng },
  { path: '/insanga/order/historysearch', name: 'HistorySearch', component: insanga.HistorySearch },
  { path: '/insanga/order/deliverytrack', name: 'DeliveryTrack', component: insanga.DeliveryTrack },
  { path: '/insanga/monthdata/periodbynewcustomerstatus', name: 'PeriodByNewCustomerStatus', component: insanga.PeriodByNewCustomerStatus },
  { path: '/insanga/monthdata/monthsalesstatus', name: 'MonthSalesStatus', component: insanga.MonthSalesStatus },
  { path: '/insanga/monthdata/monthinstatus', name: 'MonthInStatus', component: insanga.MonthInStatus },
  { path: '/insanga/monthdata/managerbysalesstatus', name: 'ManagerBySalesStatus', component: insanga.ManagerBySalesStatus },
  { path: '/insanga/monthdata/goodsbysalesabc', name: 'GoodsBySalesAbc', component: insanga.GoodsBySalesAbc },
  { path: '/insanga/monthdata/customermileagestatus', name: 'CustomerMileageStatus', component: insanga.CustomerMileageStatus },
  { path: '/insanga/monthdata/customerbysalesabc', name: 'CustomerBySalesAbc', component: insanga.CustomerBySalesAbc },
  { path: '/insanga/monthdata/customerbymidcatesalesstatus', name: 'CustomerByMidCateSalesStatus', component: insanga.CustomerByMidCateSalesStatus },
  { path: '/insanga/monthdata/customerbirthdaysearch', name: 'CustomerBirthdaySearch', component: insanga.CustomerBirthdaySearch },
  { path: '/insanga/monthdata/agentstockstatus', name: 'AgentStockStatus', component: insanga.AgentStockStatus },
  { path: '/insanga/main', name: 'Main', component: insanga.Main },
  { path: '/insanga/inputmng/ordermng', name: 'OrderMng', component: insanga.OrderMng },
  { path: '/insanga/inputmng/incomingslipsmng', name: 'IncomingSlipsMng', component: insanga.IncomingSlipsMng },
  { path: '/insanga/goods/pricemng', name: 'PriceMng', component: insanga.PriceMng },
  { path: '/insanga/goods/goodsviewdetail', name: 'GoodsViewDetail', component: insanga.GoodsViewDetail },
  { path: '/insanga/goods/goodsregist', name: 'GoodsRegist', component: insanga.GoodsRegist },
  { path: '/insanga/dev/pub/layouttype3', name: 'LayoutType3', component: insanga.LayoutType3 },
  { path: '/insanga/dev/pub/layouttype2', name: 'LayoutType2', component: insanga.LayoutType2 },
  { path: '/insanga/dev/pub/layouttype1', name: 'LayoutType1', component: insanga.LayoutType1 },
  { path: '/insanga/dev/pub/components', name: 'Components', component: insanga.Components },
  { path: '/insanga/dashboard', name: 'DashBoard', component: insanga.DashBoard },
  { path: '/insanga/dashboard/type3', name: 'Type3', component: insanga.Type3 },
  { path: '/insanga/dashboard/type2', name: 'Type2', component: insanga.Type2 },
  { path: '/insanga/dashboard/type1', name: 'Type1', component: insanga.Type1 },
  { path: '/insanga/dailydata/shipinstatus', name: 'ShipInStatus', component: insanga.ShipInStatus },
  { path: '/insanga/dailydata/salesstatus', name: 'SalesStatus', component: insanga.SalesStatus },
  { path: '/insanga/dailydata/salespersonausipt', name: 'SalesPersonAusIpt', component: insanga.SalesPersonAusIpt },
  { path: '/insanga/dailydata/receiptsstatus', name: 'ReceiptsStatus', component: insanga.ReceiptsStatus },
  { path: '/insanga/dailydata/orderbyshipstatus', name: 'OrderByShipStatus', component: insanga.OrderByShipStatus },
  { path: '/insanga/dailydata/onlinesales', name: 'OnlineSales', component: insanga.OnlineSales },
  { path: '/insanga/dailydata/gwpusagestatus', name: 'GwpUsageStatus', component: insanga.GwpUsageStatus },
  { path: '/insanga/dailydata/checkordershiphiistory', name: 'CheckOrderShipHiistory', component: insanga.CheckOrderShipHiistory },
  { path: '/insanga/dailydata/agentstockmovestatus', name: 'AgentStockMoveStatus', component: insanga.AgentStockMoveStatus },
  { path: '/insanga/customer/skinworrysearch', name: 'SkinWorrySearch', component: insanga.SkinWorrySearch },
  { path: '/insanga/customer/repurchbystatus', name: 'RepurchByStatus', component: insanga.RepurchByStatus },
  { path: '/insanga/customer/purchbysalesstatus', name: 'PurchBySalesStatus', component: insanga.PurchBySalesStatus },
  { path: '/insanga/customer/purchbycustcntstatus', name: 'PurchByCustCntStatus', component: insanga.PurchByCustCntStatus },
  { path: '/insanga/customer/productsearch', name: 'ProductSearch', component: insanga.ProductSearch },
  { path: '/insanga/customer/monthretentionstatus', name: 'MonthRetentionStatus', component: insanga.MonthRetentionStatus },
  { path: '/insanga/customer/monthnewcustpurchcnt', name: 'MonthNewCustPurchCnt', component: insanga.MonthNewCustPurchCnt },
  { path: '/insanga/customer/monthexistcustpurchcnt', name: 'MonthExistCustPurchCnt', component: insanga.MonthExistCustPurchCnt },
  { path: '/insanga/customer/gradesalesstatus', name: 'GradeSalesStatus', component: insanga.GradeSalesStatus },
  { path: '/insanga/customer/custstatus', name: 'CustStatus', component: insanga.CustStatus },
  { path: '/insanga/customer/custperformance', name: 'CustPerformance', component: insanga.CustPerformance },
  { path: '/insanga/customer/customermanage', name: 'CustomerManage', component: insanga.CustomerManage },
  { path: '/insanga/customer/customerinfosearch', name: 'CustomerInfoSearch', component: insanga.CustomerInfoSearch },
  { path: '/insanga/customer/custmileagestatus', name: 'CustMileageStatus', component: insanga.CustMileageStatus },
  { path: '/insanga/customer/custmileagemng', name: 'CustMileageMng', component: insanga.CustMileageMng },
  { path: '/insanga/customer/custinformation', name: 'CustInformation', component: insanga.CustInformation },
  { path: '/insanga/customer/custbirthday', name: 'CustBirthday', component: insanga.CustBirthday },
  { path: '/insanga/customer/brandsearch', name: 'BrandSearch', component: insanga.BrandSearch },
  { path: '/insanga/customer/agentweekcustcnt', name: 'AgentWeekCustCnt', component: insanga.AgentWeekCustCnt },
  { path: '/insanga/customer/agentperiodcustcnt', name: 'AgentPeriodCustCnt', component: insanga.AgentPeriodCustCnt },
  { path: '/insanga/customer/agentmonthcustcnt', name: 'AgentMonthCustCnt', component: insanga.AgentMonthCustCnt },
  { path: '/insanga/customer/agebysalesstatus', name: 'AgeBySalesStatus', component: insanga.AgeBySalesStatus },
  { path: '/home', name: 'Home', component: root.Home },
  { path: '/', name: 'HomeRoot', component: root.Home },
  { path: '/home/dashboard', name: 'DashBoard', component: home.DashBoard },
  { path: '/home/announce/announceboard', name: 'AnnounceBoard', component: home.AnnounceBoard },
  { path: '/crm/dashboard', name: 'DashBoard', component: crm.DashBoard },
  { path: '/about', name: 'About', component: root.About },
];

export default routeConfig;
export { routeConfig };
